import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { ShoppingBag } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { sanitizeTheme } from "@/lib/storefront";

export const Route = createFileRoute("/s/$slug")({ component: Storefront });
type StorefrontData = { store: { name: string; slug: string; logo_url: string | null; description: string | null; theme: unknown; whatsapp: string | null }; sections: { id: string; type: string; config: { headline?: string; subheadline?: string; cta?: string } }[]; listings: { id: string; retail_price: number | null; product: { name: string; images: string[] } | null }[] };
function Storefront() { const { slug } = Route.useParams(); const q = useQuery({ queryKey:["public-store",slug], queryFn: async () => { const { data,error }=await supabase.rpc("public_storefront",{_slug:slug}); if(error) throw error; return data as unknown as StorefrontData | null; } }); if(q.isLoading) return <main className="min-h-screen bg-white p-8">Carregando loja…</main>; if(!q.data) return <main className="grid min-h-screen place-items-center bg-white p-8"><div className="text-center"><h1 className="text-2xl font-bold">Loja indisponível</h1><p className="mt-2 text-slate-500">Este endereço não está publicado.</p></div></main>; const t=sanitizeTheme(q.data.store.theme); const hero=q.data.sections.find(s=>s.type==="hero"); return <main style={{background:t.background,color:t.text,fontFamily:t.fontBody}} className="min-h-screen"><header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><div className="flex items-center gap-3">{q.data.store.logo_url?<img src={q.data.store.logo_url} alt="" className="h-9 w-9 rounded-full object-cover"/>:null}<b className="text-lg">{q.data.store.name}</b></div><ShoppingBag className="h-5 w-5"/></header><section className="mx-auto max-w-7xl px-5 py-16 sm:py-24"><p className="text-sm font-semibold" style={{color:t.accent}}>NOVA COLEÇÃO</p><h1 className="mt-3 max-w-3xl text-4xl font-bold tracking-tight sm:text-6xl">{hero?.config.headline ?? q.data.store.name}</h1><p className="mt-5 max-w-xl text-lg opacity-70">{hero?.config.subheadline ?? q.data.store.description}</p></section><section className="mx-auto max-w-7xl px-5 pb-16"><h2 className="text-2xl font-bold">Produtos em destaque</h2><div className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-4">{q.data.listings.map(l=><article key={l.id} className="overflow-hidden rounded-xl border" style={{borderColor:t.border}}><div className="aspect-square bg-slate-100">{l.product?.images?.[0]&&<img src={l.product.images[0]} alt="" className="h-full w-full object-cover"/>}</div><div className="p-3"><b className="line-clamp-2 text-sm">{l.product?.name}</b>{l.retail_price!=null&&<p className="mt-1 font-semibold">R$ {Number(l.retail_price).toFixed(2).replace('.',',')}</p>}</div></article>)}</div></section></main>; }
