/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminSplatRouteImport } from './routes/_authenticated/admin/$'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin/auditoria'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin/categorias'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin/configuracoes'
import { Route as AuthenticatedAdminEstoqueRouteImport } from './routes/_authenticated/admin/estoque'
import { Route as AuthenticatedAdminIaRouteImport } from './routes/_authenticated/admin/ia'
import { Route as AuthenticatedAdminLojasRouteImport } from './routes/_authenticated/admin/lojas'
import { Route as AuthenticatedAdminMarcasRouteImport } from './routes/_authenticated/admin/marcas'
import { Route as AuthenticatedAdminModalidadesRouteImport } from './routes/_authenticated/admin/modalidades'
import { Route as AuthenticatedAdminOfertasRouteImport } from './routes/_authenticated/admin/ofertas'
import { Route as AuthenticatedAdminOperacionalRouteImport } from './routes/_authenticated/admin/operacional'
import { Route as AuthenticatedAdminPermissoesRouteImport } from './routes/_authenticated/admin/permissoes'
import { Route as AuthenticatedAdminPrecosRouteImport } from './routes/_authenticated/admin/precos'
import { Route as AuthenticatedAdminProdutosRouteImport } from './routes/_authenticated/admin/produtos'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as SSlugBuscaRouteImport } from './routes/s.$slug.busca'
import { Route as SSlugCarrinhoRouteImport } from './routes/s.$slug.carrinho'
import { Route as SSlugCatalogoRouteImport } from './routes/s.$slug.catalogo'
import { Route as AuthenticatedAdminClientesIndexRouteImport } from './routes/_authenticated/admin/clientes/index'
import { Route as AuthenticatedAdminClientesOrgIdRouteImport } from './routes/_authenticated/admin/clientes/$orgId'
import { Route as AuthenticatedAdminClientesNovoRouteImport } from './routes/_authenticated/admin/clientes/novo'
import { Route as AuthenticatedAdminEmpresasIndexRouteImport } from './routes/_authenticated/admin/empresas/index'
import { Route as AuthenticatedAdminEmpresasOrgIdRouteImport } from './routes/_authenticated/admin/empresas/$orgId'
import { Route as AuthenticatedAdminEmpresasNovaRouteImport } from './routes/_authenticated/admin/empresas/nova'
import { Route as AuthenticatedAdminFinanceiroIndexRouteImport } from './routes/_authenticated/admin/financeiro/index'
import { Route as AuthenticatedAdminFinanceiroAllocationsRouteImport } from './routes/_authenticated/admin/financeiro/allocations'
import { Route as AuthenticatedAdminFinanceiroContasRouteImport } from './routes/_authenticated/admin/financeiro/contas'
import { Route as AuthenticatedAdminFinanceiroLedgerRouteImport } from './routes/_authenticated/admin/financeiro/ledger'
import { Route as AuthenticatedAdminFinanceiroRecebiveisRouteImport } from './routes/_authenticated/admin/financeiro/recebiveis'
import { Route as AuthenticatedAdminFinanceiroRepassesRouteImport } from './routes/_authenticated/admin/financeiro/repasses'
import { Route as AuthenticatedAdminFinanceiroTransacoesRouteImport } from './routes/_authenticated/admin/financeiro/transacoes'
import { Route as AuthenticatedAdminFornecedoresIndexRouteImport } from './routes/_authenticated/admin/fornecedores/index'
import { Route as AuthenticatedAdminFornecedoresOrgIdRouteImport } from './routes/_authenticated/admin/fornecedores/$orgId'
import { Route as AuthenticatedAdminFornecedoresNovoRouteImport } from './routes/_authenticated/admin/fornecedores/novo'
import { Route as AuthenticatedAdminProdutosProductIdRouteImport } from './routes/_authenticated/admin/produtos.$productId'
import { Route as SSlugCategoriasCategorySlugRouteImport } from './routes/s.$slug.categorias.$categorySlug'
import { Route as SSlugColecoesCollectionSlugRouteImport } from './routes/s.$slug.colecoes.$collectionSlug'
import { Route as SSlugPaginasPageSlugRouteImport } from './routes/s.$slug.paginas.$pageSlug'
import { Route as SSlugProdutosProductSlugRouteImport } from './routes/s.$slug.produtos.$productSlug'
import { Route as AuthenticatedAdminLojasStoreIdBuilderRouteImport } from './routes/_authenticated/admin/lojas.$storeId.builder'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSplatRoute = AuthenticatedAdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEstoqueRoute =
  AuthenticatedAdminEstoqueRouteImport.update({
    id: '/estoque',
    path: '/estoque',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIaRoute = AuthenticatedAdminIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminLojasRoute = AuthenticatedAdminLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminMarcasRoute =
  AuthenticatedAdminMarcasRouteImport.update({
    id: '/marcas',
    path: '/marcas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminModalidadesRoute =
  AuthenticatedAdminModalidadesRouteImport.update({
    id: '/modalidades',
    path: '/modalidades',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOfertasRoute =
  AuthenticatedAdminOfertasRouteImport.update({
    id: '/ofertas',
    path: '/ofertas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOperacionalRoute =
  AuthenticatedAdminOperacionalRouteImport.update({
    id: '/operacional',
    path: '/operacional',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPermissoesRoute =
  AuthenticatedAdminPermissoesRouteImport.update({
    id: '/permissoes',
    path: '/permissoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPrecosRoute =
  AuthenticatedAdminPrecosRouteImport.update({
    id: '/precos',
    path: '/precos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProdutosRoute =
  AuthenticatedAdminProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const SSlugBuscaRoute = SSlugBuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugCarrinhoRoute = SSlugCarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugCatalogoRoute = SSlugCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => SSlugRoute,
} as any)
const AuthenticatedAdminClientesIndexRoute =
  AuthenticatedAdminClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientesOrgIdRoute =
  AuthenticatedAdminClientesOrgIdRouteImport.update({
    id: '/clientes/$orgId',
    path: '/clientes/$orgId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientesNovoRoute =
  AuthenticatedAdminClientesNovoRouteImport.update({
    id: '/clientes/novo',
    path: '/clientes/novo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmpresasIndexRoute =
  AuthenticatedAdminEmpresasIndexRouteImport.update({
    id: '/empresas/',
    path: '/empresas/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmpresasOrgIdRoute =
  AuthenticatedAdminEmpresasOrgIdRouteImport.update({
    id: '/empresas/$orgId',
    path: '/empresas/$orgId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmpresasNovaRoute =
  AuthenticatedAdminEmpresasNovaRouteImport.update({
    id: '/empresas/nova',
    path: '/empresas/nova',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroIndexRoute =
  AuthenticatedAdminFinanceiroIndexRouteImport.update({
    id: '/financeiro/',
    path: '/financeiro/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroAllocationsRoute =
  AuthenticatedAdminFinanceiroAllocationsRouteImport.update({
    id: '/financeiro/allocations',
    path: '/financeiro/allocations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroContasRoute =
  AuthenticatedAdminFinanceiroContasRouteImport.update({
    id: '/financeiro/contas',
    path: '/financeiro/contas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroLedgerRoute =
  AuthenticatedAdminFinanceiroLedgerRouteImport.update({
    id: '/financeiro/ledger',
    path: '/financeiro/ledger',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroRecebiveisRoute =
  AuthenticatedAdminFinanceiroRecebiveisRouteImport.update({
    id: '/financeiro/recebiveis',
    path: '/financeiro/recebiveis',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroRepassesRoute =
  AuthenticatedAdminFinanceiroRepassesRouteImport.update({
    id: '/financeiro/repasses',
    path: '/financeiro/repasses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroTransacoesRoute =
  AuthenticatedAdminFinanceiroTransacoesRouteImport.update({
    id: '/financeiro/transacoes',
    path: '/financeiro/transacoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFornecedoresIndexRoute =
  AuthenticatedAdminFornecedoresIndexRouteImport.update({
    id: '/fornecedores/',
    path: '/fornecedores/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFornecedoresOrgIdRoute =
  AuthenticatedAdminFornecedoresOrgIdRouteImport.update({
    id: '/fornecedores/$orgId',
    path: '/fornecedores/$orgId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFornecedoresNovoRoute =
  AuthenticatedAdminFornecedoresNovoRouteImport.update({
    id: '/fornecedores/novo',
    path: '/fornecedores/novo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProdutosProductIdRoute =
  AuthenticatedAdminProdutosProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AuthenticatedAdminProdutosRoute,
  } as any)
const SSlugCategoriasCategorySlugRoute =
  SSlugCategoriasCategorySlugRouteImport.update({
    id: '/categorias/$categorySlug',
    path: '/categorias/$categorySlug',
    getParentRoute: () => SSlugRoute,
  } as any)
const SSlugColecoesCollectionSlugRoute =
  SSlugColecoesCollectionSlugRouteImport.update({
    id: '/colecoes/$collectionSlug',
    path: '/colecoes/$collectionSlug',
    getParentRoute: () => SSlugRoute,
  } as any)
const SSlugPaginasPageSlugRoute = SSlugPaginasPageSlugRouteImport.update({
  id: '/paginas/$pageSlug',
  path: '/paginas/$pageSlug',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugProdutosProductSlugRoute =
  SSlugProdutosProductSlugRouteImport.update({
    id: '/produtos/$productSlug',
    path: '/produtos/$productSlug',
    getParentRoute: () => SSlugRoute,
  } as any)
const AuthenticatedAdminLojasStoreIdBuilderRoute =
  AuthenticatedAdminLojasStoreIdBuilderRouteImport.update({
    id: '/$storeId/builder',
    path: '/$storeId/builder',
    getParentRoute: () => AuthenticatedAdminLojasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/s/$slug': typeof SSlugRouteWithChildren
  '/admin/$': typeof AuthenticatedAdminSplatRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/ia': typeof AuthenticatedAdminIaRoute
  '/admin/lojas': typeof AuthenticatedAdminLojasRouteWithChildren
  '/admin/marcas': typeof AuthenticatedAdminMarcasRoute
  '/admin/modalidades': typeof AuthenticatedAdminModalidadesRoute
  '/admin/ofertas': typeof AuthenticatedAdminOfertasRoute
  '/admin/operacional': typeof AuthenticatedAdminOperacionalRoute
  '/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/admin/precos': typeof AuthenticatedAdminPrecosRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRouteWithChildren
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/s/$slug/busca': typeof SSlugBuscaRoute
  '/s/$slug/carrinho': typeof SSlugCarrinhoRoute
  '/s/$slug/catalogo': typeof SSlugCatalogoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/clientes/$orgId': typeof AuthenticatedAdminClientesOrgIdRoute
  '/admin/clientes/novo': typeof AuthenticatedAdminClientesNovoRoute
  '/admin/empresas/$orgId': typeof AuthenticatedAdminEmpresasOrgIdRoute
  '/admin/empresas/nova': typeof AuthenticatedAdminEmpresasNovaRoute
  '/admin/financeiro/allocations': typeof AuthenticatedAdminFinanceiroAllocationsRoute
  '/admin/financeiro/contas': typeof AuthenticatedAdminFinanceiroContasRoute
  '/admin/financeiro/ledger': typeof AuthenticatedAdminFinanceiroLedgerRoute
  '/admin/financeiro/recebiveis': typeof AuthenticatedAdminFinanceiroRecebiveisRoute
  '/admin/financeiro/repasses': typeof AuthenticatedAdminFinanceiroRepassesRoute
  '/admin/financeiro/transacoes': typeof AuthenticatedAdminFinanceiroTransacoesRoute
  '/admin/fornecedores/$orgId': typeof AuthenticatedAdminFornecedoresOrgIdRoute
  '/admin/fornecedores/novo': typeof AuthenticatedAdminFornecedoresNovoRoute
  '/admin/produtos/$productId': typeof AuthenticatedAdminProdutosProductIdRoute
  '/s/$slug/categorias/$categorySlug': typeof SSlugCategoriasCategorySlugRoute
  '/s/$slug/colecoes/$collectionSlug': typeof SSlugColecoesCollectionSlugRoute
  '/s/$slug/paginas/$pageSlug': typeof SSlugPaginasPageSlugRoute
  '/s/$slug/produtos/$productSlug': typeof SSlugProdutosProductSlugRoute
  '/admin/clientes/': typeof AuthenticatedAdminClientesIndexRoute
  '/admin/empresas/': typeof AuthenticatedAdminEmpresasIndexRoute
  '/admin/financeiro/': typeof AuthenticatedAdminFinanceiroIndexRoute
  '/admin/fornecedores/': typeof AuthenticatedAdminFornecedoresIndexRoute
  '/admin/lojas/$storeId/builder': typeof AuthenticatedAdminLojasStoreIdBuilderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/admin/$': typeof AuthenticatedAdminSplatRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/ia': typeof AuthenticatedAdminIaRoute
  '/admin/lojas': typeof AuthenticatedAdminLojasRouteWithChildren
  '/admin/marcas': typeof AuthenticatedAdminMarcasRoute
  '/admin/modalidades': typeof AuthenticatedAdminModalidadesRoute
  '/admin/ofertas': typeof AuthenticatedAdminOfertasRoute
  '/admin/operacional': typeof AuthenticatedAdminOperacionalRoute
  '/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/admin/precos': typeof AuthenticatedAdminPrecosRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRouteWithChildren
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/s/$slug/busca': typeof SSlugBuscaRoute
  '/s/$slug/carrinho': typeof SSlugCarrinhoRoute
  '/s/$slug/catalogo': typeof SSlugCatalogoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/clientes/$orgId': typeof AuthenticatedAdminClientesOrgIdRoute
  '/admin/clientes/novo': typeof AuthenticatedAdminClientesNovoRoute
  '/admin/empresas/$orgId': typeof AuthenticatedAdminEmpresasOrgIdRoute
  '/admin/empresas/nova': typeof AuthenticatedAdminEmpresasNovaRoute
  '/admin/financeiro/allocations': typeof AuthenticatedAdminFinanceiroAllocationsRoute
  '/admin/financeiro/contas': typeof AuthenticatedAdminFinanceiroContasRoute
  '/admin/financeiro/ledger': typeof AuthenticatedAdminFinanceiroLedgerRoute
  '/admin/financeiro/recebiveis': typeof AuthenticatedAdminFinanceiroRecebiveisRoute
  '/admin/financeiro/repasses': typeof AuthenticatedAdminFinanceiroRepassesRoute
  '/admin/financeiro/transacoes': typeof AuthenticatedAdminFinanceiroTransacoesRoute
  '/admin/fornecedores/$orgId': typeof AuthenticatedAdminFornecedoresOrgIdRoute
  '/admin/fornecedores/novo': typeof AuthenticatedAdminFornecedoresNovoRoute
  '/admin/produtos/$productId': typeof AuthenticatedAdminProdutosProductIdRoute
  '/s/$slug/categorias/$categorySlug': typeof SSlugCategoriasCategorySlugRoute
  '/s/$slug/colecoes/$collectionSlug': typeof SSlugColecoesCollectionSlugRoute
  '/s/$slug/paginas/$pageSlug': typeof SSlugPaginasPageSlugRoute
  '/s/$slug/produtos/$productSlug': typeof SSlugProdutosProductSlugRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesIndexRoute
  '/admin/empresas': typeof AuthenticatedAdminEmpresasIndexRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroIndexRoute
  '/admin/fornecedores': typeof AuthenticatedAdminFornecedoresIndexRoute
  '/admin/lojas/$storeId/builder': typeof AuthenticatedAdminLojasStoreIdBuilderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/s/$slug': typeof SSlugRouteWithChildren
  '/_authenticated/admin/$': typeof AuthenticatedAdminSplatRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/_authenticated/admin/ia': typeof AuthenticatedAdminIaRoute
  '/_authenticated/admin/lojas': typeof AuthenticatedAdminLojasRouteWithChildren
  '/_authenticated/admin/marcas': typeof AuthenticatedAdminMarcasRoute
  '/_authenticated/admin/modalidades': typeof AuthenticatedAdminModalidadesRoute
  '/_authenticated/admin/ofertas': typeof AuthenticatedAdminOfertasRoute
  '/_authenticated/admin/operacional': typeof AuthenticatedAdminOperacionalRoute
  '/_authenticated/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/_authenticated/admin/precos': typeof AuthenticatedAdminPrecosRoute
  '/_authenticated/admin/produtos': typeof AuthenticatedAdminProdutosRouteWithChildren
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/s/$slug/busca': typeof SSlugBuscaRoute
  '/s/$slug/carrinho': typeof SSlugCarrinhoRoute
  '/s/$slug/catalogo': typeof SSlugCatalogoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/clientes/$orgId': typeof AuthenticatedAdminClientesOrgIdRoute
  '/_authenticated/admin/clientes/novo': typeof AuthenticatedAdminClientesNovoRoute
  '/_authenticated/admin/empresas/$orgId': typeof AuthenticatedAdminEmpresasOrgIdRoute
  '/_authenticated/admin/empresas/nova': typeof AuthenticatedAdminEmpresasNovaRoute
  '/_authenticated/admin/financeiro/allocations': typeof AuthenticatedAdminFinanceiroAllocationsRoute
  '/_authenticated/admin/financeiro/contas': typeof AuthenticatedAdminFinanceiroContasRoute
  '/_authenticated/admin/financeiro/ledger': typeof AuthenticatedAdminFinanceiroLedgerRoute
  '/_authenticated/admin/financeiro/recebiveis': typeof AuthenticatedAdminFinanceiroRecebiveisRoute
  '/_authenticated/admin/financeiro/repasses': typeof AuthenticatedAdminFinanceiroRepassesRoute
  '/_authenticated/admin/financeiro/transacoes': typeof AuthenticatedAdminFinanceiroTransacoesRoute
  '/_authenticated/admin/fornecedores/$orgId': typeof AuthenticatedAdminFornecedoresOrgIdRoute
  '/_authenticated/admin/fornecedores/novo': typeof AuthenticatedAdminFornecedoresNovoRoute
  '/_authenticated/admin/produtos/$productId': typeof AuthenticatedAdminProdutosProductIdRoute
  '/s/$slug/categorias/$categorySlug': typeof SSlugCategoriasCategorySlugRoute
  '/s/$slug/colecoes/$collectionSlug': typeof SSlugColecoesCollectionSlugRoute
  '/s/$slug/paginas/$pageSlug': typeof SSlugPaginasPageSlugRoute
  '/s/$slug/produtos/$productSlug': typeof SSlugProdutosProductSlugRoute
  '/_authenticated/admin/clientes/': typeof AuthenticatedAdminClientesIndexRoute
  '/_authenticated/admin/empresas/': typeof AuthenticatedAdminEmpresasIndexRoute
  '/_authenticated/admin/financeiro/': typeof AuthenticatedAdminFinanceiroIndexRoute
  '/_authenticated/admin/fornecedores/': typeof AuthenticatedAdminFornecedoresIndexRoute
  '/_authenticated/admin/lojas/$storeId/builder': typeof AuthenticatedAdminLojasStoreIdBuilderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/criar-conta'
    | '/entrar'
    | '/admin'
    | '/s/$slug'
    | '/admin/$'
    | '/admin/auditoria'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/estoque'
    | '/admin/ia'
    | '/admin/lojas'
    | '/admin/marcas'
    | '/admin/modalidades'
    | '/admin/ofertas'
    | '/admin/operacional'
    | '/admin/permissoes'
    | '/admin/precos'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/s/$slug/busca'
    | '/s/$slug/carrinho'
    | '/s/$slug/catalogo'
    | '/admin/'
    | '/admin/clientes/$orgId'
    | '/admin/clientes/novo'
    | '/admin/empresas/$orgId'
    | '/admin/empresas/nova'
    | '/admin/financeiro/allocations'
    | '/admin/financeiro/contas'
    | '/admin/financeiro/ledger'
    | '/admin/financeiro/recebiveis'
    | '/admin/financeiro/repasses'
    | '/admin/financeiro/transacoes'
    | '/admin/fornecedores/$orgId'
    | '/admin/fornecedores/novo'
    | '/admin/produtos/$productId'
    | '/s/$slug/categorias/$categorySlug'
    | '/s/$slug/colecoes/$collectionSlug'
    | '/s/$slug/paginas/$pageSlug'
    | '/s/$slug/produtos/$productSlug'
    | '/admin/clientes/'
    | '/admin/empresas/'
    | '/admin/financeiro/'
    | '/admin/fornecedores/'
    | '/admin/lojas/$storeId/builder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/criar-conta'
    | '/entrar'
    | '/s/$slug'
    | '/admin/$'
    | '/admin/auditoria'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/estoque'
    | '/admin/ia'
    | '/admin/lojas'
    | '/admin/marcas'
    | '/admin/modalidades'
    | '/admin/ofertas'
    | '/admin/operacional'
    | '/admin/permissoes'
    | '/admin/precos'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/s/$slug/busca'
    | '/s/$slug/carrinho'
    | '/s/$slug/catalogo'
    | '/admin'
    | '/admin/clientes/$orgId'
    | '/admin/clientes/novo'
    | '/admin/empresas/$orgId'
    | '/admin/empresas/nova'
    | '/admin/financeiro/allocations'
    | '/admin/financeiro/contas'
    | '/admin/financeiro/ledger'
    | '/admin/financeiro/recebiveis'
    | '/admin/financeiro/repasses'
    | '/admin/financeiro/transacoes'
    | '/admin/fornecedores/$orgId'
    | '/admin/fornecedores/novo'
    | '/admin/produtos/$productId'
    | '/s/$slug/categorias/$categorySlug'
    | '/s/$slug/colecoes/$collectionSlug'
    | '/s/$slug/paginas/$pageSlug'
    | '/s/$slug/produtos/$productSlug'
    | '/admin/clientes'
    | '/admin/empresas'
    | '/admin/financeiro'
    | '/admin/fornecedores'
    | '/admin/lojas/$storeId/builder'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/criar-conta'
    | '/entrar'
    | '/_authenticated/admin'
    | '/s/$slug'
    | '/_authenticated/admin/$'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/estoque'
    | '/_authenticated/admin/ia'
    | '/_authenticated/admin/lojas'
    | '/_authenticated/admin/marcas'
    | '/_authenticated/admin/modalidades'
    | '/_authenticated/admin/ofertas'
    | '/_authenticated/admin/operacional'
    | '/_authenticated/admin/permissoes'
    | '/_authenticated/admin/precos'
    | '/_authenticated/admin/produtos'
    | '/_authenticated/admin/usuarios'
    | '/s/$slug/busca'
    | '/s/$slug/carrinho'
    | '/s/$slug/catalogo'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/clientes/$orgId'
    | '/_authenticated/admin/clientes/novo'
    | '/_authenticated/admin/empresas/$orgId'
    | '/_authenticated/admin/empresas/nova'
    | '/_authenticated/admin/financeiro/allocations'
    | '/_authenticated/admin/financeiro/contas'
    | '/_authenticated/admin/financeiro/ledger'
    | '/_authenticated/admin/financeiro/recebiveis'
    | '/_authenticated/admin/financeiro/repasses'
    | '/_authenticated/admin/financeiro/transacoes'
    | '/_authenticated/admin/fornecedores/$orgId'
    | '/_authenticated/admin/fornecedores/novo'
    | '/_authenticated/admin/produtos/$productId'
    | '/s/$slug/categorias/$categorySlug'
    | '/s/$slug/colecoes/$collectionSlug'
    | '/s/$slug/paginas/$pageSlug'
    | '/s/$slug/produtos/$productSlug'
    | '/_authenticated/admin/clientes/'
    | '/_authenticated/admin/empresas/'
    | '/_authenticated/admin/financeiro/'
    | '/_authenticated/admin/fornecedores/'
    | '/_authenticated/admin/lojas/$storeId/builder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CriarContaRoute: typeof CriarContaRoute
  EntrarRoute: typeof EntrarRoute
  SSlugRoute: typeof SSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/$': {
      id: '/_authenticated/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AuthenticatedAdminSplatRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/estoque': {
      id: '/_authenticated/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AuthenticatedAdminEstoqueRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ia': {
      id: '/_authenticated/admin/ia'
      path: '/ia'
      fullPath: '/admin/ia'
      preLoaderRoute: typeof AuthenticatedAdminIaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/lojas': {
      id: '/_authenticated/admin/lojas'
      path: '/lojas'
      fullPath: '/admin/lojas'
      preLoaderRoute: typeof AuthenticatedAdminLojasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/marcas': {
      id: '/_authenticated/admin/marcas'
      path: '/marcas'
      fullPath: '/admin/marcas'
      preLoaderRoute: typeof AuthenticatedAdminMarcasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/modalidades': {
      id: '/_authenticated/admin/modalidades'
      path: '/modalidades'
      fullPath: '/admin/modalidades'
      preLoaderRoute: typeof AuthenticatedAdminModalidadesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ofertas': {
      id: '/_authenticated/admin/ofertas'
      path: '/ofertas'
      fullPath: '/admin/ofertas'
      preLoaderRoute: typeof AuthenticatedAdminOfertasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/operacional': {
      id: '/_authenticated/admin/operacional'
      path: '/operacional'
      fullPath: '/admin/operacional'
      preLoaderRoute: typeof AuthenticatedAdminOperacionalRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/permissoes': {
      id: '/_authenticated/admin/permissoes'
      path: '/permissoes'
      fullPath: '/admin/permissoes'
      preLoaderRoute: typeof AuthenticatedAdminPermissoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/precos': {
      id: '/_authenticated/admin/precos'
      path: '/precos'
      fullPath: '/admin/precos'
      preLoaderRoute: typeof AuthenticatedAdminPrecosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/produtos': {
      id: '/_authenticated/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthenticatedAdminProdutosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/s/$slug/busca': {
      id: '/s/$slug/busca'
      path: '/busca'
      fullPath: '/s/$slug/busca'
      preLoaderRoute: typeof SSlugBuscaRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/carrinho': {
      id: '/s/$slug/carrinho'
      path: '/carrinho'
      fullPath: '/s/$slug/carrinho'
      preLoaderRoute: typeof SSlugCarrinhoRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/catalogo': {
      id: '/s/$slug/catalogo'
      path: '/catalogo'
      fullPath: '/s/$slug/catalogo'
      preLoaderRoute: typeof SSlugCatalogoRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/_authenticated/admin/clientes/': {
      id: '/_authenticated/admin/clientes/'
      path: '/clientes'
      fullPath: '/admin/clientes/'
      preLoaderRoute: typeof AuthenticatedAdminClientesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clientes/$orgId': {
      id: '/_authenticated/admin/clientes/$orgId'
      path: '/clientes/$orgId'
      fullPath: '/admin/clientes/$orgId'
      preLoaderRoute: typeof AuthenticatedAdminClientesOrgIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clientes/novo': {
      id: '/_authenticated/admin/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/admin/clientes/novo'
      preLoaderRoute: typeof AuthenticatedAdminClientesNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/empresas/': {
      id: '/_authenticated/admin/empresas/'
      path: '/empresas'
      fullPath: '/admin/empresas/'
      preLoaderRoute: typeof AuthenticatedAdminEmpresasIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/empresas/$orgId': {
      id: '/_authenticated/admin/empresas/$orgId'
      path: '/empresas/$orgId'
      fullPath: '/admin/empresas/$orgId'
      preLoaderRoute: typeof AuthenticatedAdminEmpresasOrgIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/empresas/nova': {
      id: '/_authenticated/admin/empresas/nova'
      path: '/empresas/nova'
      fullPath: '/admin/empresas/nova'
      preLoaderRoute: typeof AuthenticatedAdminEmpresasNovaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financeiro/': {
      id: '/_authenticated/admin/financeiro/'
      path: '/financeiro'
      fullPath: '/admin/financeiro/'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financeiro/allocations': {
      id: '/_authenticated/admin/financeiro/allocations'
      path: '/financeiro/allocations'
      fullPath: '/admin/financeiro/allocations'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroAllocationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financeiro/contas': {
      id: '/_authenticated/admin/financeiro/contas'
      path: '/financeiro/contas'
      fullPath: '/admin/financeiro/contas'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroContasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financeiro/ledger': {
      id: '/_authenticated/admin/financeiro/ledger'
      path: '/financeiro/ledger'
      fullPath: '/admin/financeiro/ledger'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroLedgerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financeiro/recebiveis': {
      id: '/_authenticated/admin/financeiro/recebiveis'
      path: '/financeiro/recebiveis'
      fullPath: '/admin/financeiro/recebiveis'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRecebiveisRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financeiro/repasses': {
      id: '/_authenticated/admin/financeiro/repasses'
      path: '/financeiro/repasses'
      fullPath: '/admin/financeiro/repasses'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRepassesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financeiro/transacoes': {
      id: '/_authenticated/admin/financeiro/transacoes'
      path: '/financeiro/transacoes'
      fullPath: '/admin/financeiro/transacoes'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroTransacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/fornecedores/': {
      id: '/_authenticated/admin/fornecedores/'
      path: '/fornecedores'
      fullPath: '/admin/fornecedores/'
      preLoaderRoute: typeof AuthenticatedAdminFornecedoresIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/fornecedores/$orgId': {
      id: '/_authenticated/admin/fornecedores/$orgId'
      path: '/fornecedores/$orgId'
      fullPath: '/admin/fornecedores/$orgId'
      preLoaderRoute: typeof AuthenticatedAdminFornecedoresOrgIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/fornecedores/novo': {
      id: '/_authenticated/admin/fornecedores/novo'
      path: '/fornecedores/novo'
      fullPath: '/admin/fornecedores/novo'
      preLoaderRoute: typeof AuthenticatedAdminFornecedoresNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/produtos/$productId': {
      id: '/_authenticated/admin/produtos/$productId'
      path: '/$productId'
      fullPath: '/admin/produtos/$productId'
      preLoaderRoute: typeof AuthenticatedAdminProdutosProductIdRouteImport
      parentRoute: typeof AuthenticatedAdminProdutosRoute
    }
    '/s/$slug/categorias/$categorySlug': {
      id: '/s/$slug/categorias/$categorySlug'
      path: '/categorias/$categorySlug'
      fullPath: '/s/$slug/categorias/$categorySlug'
      preLoaderRoute: typeof SSlugCategoriasCategorySlugRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/colecoes/$collectionSlug': {
      id: '/s/$slug/colecoes/$collectionSlug'
      path: '/colecoes/$collectionSlug'
      fullPath: '/s/$slug/colecoes/$collectionSlug'
      preLoaderRoute: typeof SSlugColecoesCollectionSlugRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/paginas/$pageSlug': {
      id: '/s/$slug/paginas/$pageSlug'
      path: '/paginas/$pageSlug'
      fullPath: '/s/$slug/paginas/$pageSlug'
      preLoaderRoute: typeof SSlugPaginasPageSlugRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/produtos/$productSlug': {
      id: '/s/$slug/produtos/$productSlug'
      path: '/produtos/$productSlug'
      fullPath: '/s/$slug/produtos/$productSlug'
      preLoaderRoute: typeof SSlugProdutosProductSlugRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/_authenticated/admin/lojas/$storeId/builder': {
      id: '/_authenticated/admin/lojas/$storeId/builder'
      path: '/$storeId/builder'
      fullPath: '/admin/lojas/$storeId/builder'
      preLoaderRoute: typeof AuthenticatedAdminLojasStoreIdBuilderRouteImport
      parentRoute: typeof AuthenticatedAdminLojasRoute
    }
  }
}

interface AuthenticatedAdminLojasRouteChildren {
  AuthenticatedAdminLojasStoreIdBuilderRoute: typeof AuthenticatedAdminLojasStoreIdBuilderRoute
}

const AuthenticatedAdminLojasRouteChildren: AuthenticatedAdminLojasRouteChildren =
  {
    AuthenticatedAdminLojasStoreIdBuilderRoute:
      AuthenticatedAdminLojasStoreIdBuilderRoute,
  }

const AuthenticatedAdminLojasRouteWithChildren =
  AuthenticatedAdminLojasRoute._addFileChildren(
    AuthenticatedAdminLojasRouteChildren,
  )

interface AuthenticatedAdminProdutosRouteChildren {
  AuthenticatedAdminProdutosProductIdRoute: typeof AuthenticatedAdminProdutosProductIdRoute
}

const AuthenticatedAdminProdutosRouteChildren: AuthenticatedAdminProdutosRouteChildren =
  {
    AuthenticatedAdminProdutosProductIdRoute:
      AuthenticatedAdminProdutosProductIdRoute,
  }

const AuthenticatedAdminProdutosRouteWithChildren =
  AuthenticatedAdminProdutosRoute._addFileChildren(
    AuthenticatedAdminProdutosRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminSplatRoute: typeof AuthenticatedAdminSplatRoute
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminEstoqueRoute: typeof AuthenticatedAdminEstoqueRoute
  AuthenticatedAdminIaRoute: typeof AuthenticatedAdminIaRoute
  AuthenticatedAdminLojasRoute: typeof AuthenticatedAdminLojasRouteWithChildren
  AuthenticatedAdminMarcasRoute: typeof AuthenticatedAdminMarcasRoute
  AuthenticatedAdminModalidadesRoute: typeof AuthenticatedAdminModalidadesRoute
  AuthenticatedAdminOfertasRoute: typeof AuthenticatedAdminOfertasRoute
  AuthenticatedAdminOperacionalRoute: typeof AuthenticatedAdminOperacionalRoute
  AuthenticatedAdminPermissoesRoute: typeof AuthenticatedAdminPermissoesRoute
  AuthenticatedAdminPrecosRoute: typeof AuthenticatedAdminPrecosRoute
  AuthenticatedAdminProdutosRoute: typeof AuthenticatedAdminProdutosRouteWithChildren
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminClientesOrgIdRoute: typeof AuthenticatedAdminClientesOrgIdRoute
  AuthenticatedAdminClientesNovoRoute: typeof AuthenticatedAdminClientesNovoRoute
  AuthenticatedAdminEmpresasOrgIdRoute: typeof AuthenticatedAdminEmpresasOrgIdRoute
  AuthenticatedAdminEmpresasNovaRoute: typeof AuthenticatedAdminEmpresasNovaRoute
  AuthenticatedAdminFinanceiroAllocationsRoute: typeof AuthenticatedAdminFinanceiroAllocationsRoute
  AuthenticatedAdminFinanceiroContasRoute: typeof AuthenticatedAdminFinanceiroContasRoute
  AuthenticatedAdminFinanceiroLedgerRoute: typeof AuthenticatedAdminFinanceiroLedgerRoute
  AuthenticatedAdminFinanceiroRecebiveisRoute: typeof AuthenticatedAdminFinanceiroRecebiveisRoute
  AuthenticatedAdminFinanceiroRepassesRoute: typeof AuthenticatedAdminFinanceiroRepassesRoute
  AuthenticatedAdminFinanceiroTransacoesRoute: typeof AuthenticatedAdminFinanceiroTransacoesRoute
  AuthenticatedAdminFornecedoresOrgIdRoute: typeof AuthenticatedAdminFornecedoresOrgIdRoute
  AuthenticatedAdminFornecedoresNovoRoute: typeof AuthenticatedAdminFornecedoresNovoRoute
  AuthenticatedAdminClientesIndexRoute: typeof AuthenticatedAdminClientesIndexRoute
  AuthenticatedAdminEmpresasIndexRoute: typeof AuthenticatedAdminEmpresasIndexRoute
  AuthenticatedAdminFinanceiroIndexRoute: typeof AuthenticatedAdminFinanceiroIndexRoute
  AuthenticatedAdminFornecedoresIndexRoute: typeof AuthenticatedAdminFornecedoresIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminSplatRoute: AuthenticatedAdminSplatRoute,
    AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
    AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
    AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
    AuthenticatedAdminEstoqueRoute: AuthenticatedAdminEstoqueRoute,
    AuthenticatedAdminIaRoute: AuthenticatedAdminIaRoute,
    AuthenticatedAdminLojasRoute: AuthenticatedAdminLojasRouteWithChildren,
    AuthenticatedAdminMarcasRoute: AuthenticatedAdminMarcasRoute,
    AuthenticatedAdminModalidadesRoute: AuthenticatedAdminModalidadesRoute,
    AuthenticatedAdminOfertasRoute: AuthenticatedAdminOfertasRoute,
    AuthenticatedAdminOperacionalRoute: AuthenticatedAdminOperacionalRoute,
    AuthenticatedAdminPermissoesRoute: AuthenticatedAdminPermissoesRoute,
    AuthenticatedAdminPrecosRoute: AuthenticatedAdminPrecosRoute,
    AuthenticatedAdminProdutosRoute:
      AuthenticatedAdminProdutosRouteWithChildren,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminClientesOrgIdRoute: AuthenticatedAdminClientesOrgIdRoute,
    AuthenticatedAdminClientesNovoRoute: AuthenticatedAdminClientesNovoRoute,
    AuthenticatedAdminEmpresasOrgIdRoute: AuthenticatedAdminEmpresasOrgIdRoute,
    AuthenticatedAdminEmpresasNovaRoute: AuthenticatedAdminEmpresasNovaRoute,
    AuthenticatedAdminFinanceiroAllocationsRoute:
      AuthenticatedAdminFinanceiroAllocationsRoute,
    AuthenticatedAdminFinanceiroContasRoute:
      AuthenticatedAdminFinanceiroContasRoute,
    AuthenticatedAdminFinanceiroLedgerRoute:
      AuthenticatedAdminFinanceiroLedgerRoute,
    AuthenticatedAdminFinanceiroRecebiveisRoute:
      AuthenticatedAdminFinanceiroRecebiveisRoute,
    AuthenticatedAdminFinanceiroRepassesRoute:
      AuthenticatedAdminFinanceiroRepassesRoute,
    AuthenticatedAdminFinanceiroTransacoesRoute:
      AuthenticatedAdminFinanceiroTransacoesRoute,
    AuthenticatedAdminFornecedoresOrgIdRoute:
      AuthenticatedAdminFornecedoresOrgIdRoute,
    AuthenticatedAdminFornecedoresNovoRoute:
      AuthenticatedAdminFornecedoresNovoRoute,
    AuthenticatedAdminClientesIndexRoute: AuthenticatedAdminClientesIndexRoute,
    AuthenticatedAdminEmpresasIndexRoute: AuthenticatedAdminEmpresasIndexRoute,
    AuthenticatedAdminFinanceiroIndexRoute:
      AuthenticatedAdminFinanceiroIndexRoute,
    AuthenticatedAdminFornecedoresIndexRoute:
      AuthenticatedAdminFornecedoresIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SSlugRouteChildren {
  SSlugBuscaRoute: typeof SSlugBuscaRoute
  SSlugCarrinhoRoute: typeof SSlugCarrinhoRoute
  SSlugCatalogoRoute: typeof SSlugCatalogoRoute
  SSlugCategoriasCategorySlugRoute: typeof SSlugCategoriasCategorySlugRoute
  SSlugColecoesCollectionSlugRoute: typeof SSlugColecoesCollectionSlugRoute
  SSlugPaginasPageSlugRoute: typeof SSlugPaginasPageSlugRoute
  SSlugProdutosProductSlugRoute: typeof SSlugProdutosProductSlugRoute
}

const SSlugRouteChildren: SSlugRouteChildren = {
  SSlugBuscaRoute: SSlugBuscaRoute,
  SSlugCarrinhoRoute: SSlugCarrinhoRoute,
  SSlugCatalogoRoute: SSlugCatalogoRoute,
  SSlugCategoriasCategorySlugRoute: SSlugCategoriasCategorySlugRoute,
  SSlugColecoesCollectionSlugRoute: SSlugColecoesCollectionSlugRoute,
  SSlugPaginasPageSlugRoute: SSlugPaginasPageSlugRoute,
  SSlugProdutosProductSlugRoute: SSlugProdutosProductSlugRoute,
}

const SSlugRouteWithChildren = SSlugRoute._addFileChildren(SSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CriarContaRoute: CriarContaRoute,
  EntrarRoute: EntrarRoute,
  SSlugRoute: SSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
